#**NUMPY**














1.   Numpy is freeware and open source library.
2.   It is written in C and python languages.
3.   Numpy uses less bytes of memory - so less time to process
4.   No need for type-checking while executing for Numpy hence, more speed
5.   Numpy uses continuous memory locations. So, easy access.
3.   Because of high speed Numpy is preferred for ML algorithms

Egs.: 

1.   Images - 2D arrays of nos representing pixel brightness across the area
2.   Sound clips - 1D array of intensity vs time

N-dimensional arrays are of type ndarray





In [1]:
import numpy as np

?1) Initialize [1,2,3,4] and (1,5,4,7) as arrays. Let the datatypes be initialized as int and float respectively.
      

      1.   Display the datatype of a and datatype within a
      2.   Display the dimension of a
      



In [ ]:
a = np.array([1,2,3,4], dtype = int)

In [ ]:
b = np.array((1,5,4,7), dtype = float)

In [ ]:
print(a)
print(b)

[1 2 3 4]
[1 5 4 7]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.ndim

1

?2) Initialize array [[1,2,3]
                     [4,5,6]]
    
    1. Access element 3 by indexing.

    

In [ ]:
a= np.array([[1,2,3],[4,5,6]])

In [ ]:
a[0,2]

3

##**NB:**If there is no consistency in number of elements in each dimension, the array will be considered as a single dimensional array of all the provided elements.

?3) Initialize array [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

      1. Access element 8
      2. Display the order of this array
      3. Display the number of elements in each dimension
      4. Display the total no. of elements in the array
      5. Display the memory allocation for this array
      6. Change the datatype of the array to float




In [ ]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
a[1,0,1]

8

In [ ]:
a.shape

(2, 2, 3)

In [ ]:
a.shape[0]

2

In [ ]:
a.shape[1]

2

In [ ]:
a.shape[2]

3

In [ ]:
a.size

12

In [ ]:
a.nbytes

96

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a = a.astype('float64')

In [ ]:
a.dtype

dtype('float64')

?4) Create a 1-D array of first 99 natural nos.

    1.   Recreate the above in random permutation.




In [ ]:
a = np.arange(100)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.random.permutation(np.arange(100))

array([15, 42, 33, 51, 29, 14, 49, 45, 54, 26, 81, 24, 83, 53,  1, 31, 73,
       88,  3, 94, 64, 28, 21, 12, 60, 13, 76, 65,  2, 70, 19,  6, 58, 61,
       92, 63, 17, 95, 82, 43, 79, 93, 23,  5, 59, 72, 68, 18, 55, 35, 62,
       67, 52, 99, 39, 98, 41, 16, 38, 44, 48, 91, 10, 50,  4, 66, 75, 22,
       27, 77, 36, 30, 20, 80, 90, 11, 89, 96, 32,  9, 97, 74, 40, 37, 34,
        7, 78, 85, 69, 25, 57, 47, 87, 46, 56,  8, 84,  0, 71, 86])

?5) Create a 1-D array of first 10 natural nos.


    1. Turn it into an array of order 2x5
   



In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

?5) Create a 1X10 array of random nos between 0 and 1 using rand function.

Create a matrix of order 4X2 with random nos between 0 and 1 using rand function.

In [ ]:
np.random.rand(10)

array([0.57307107, 0.09191661, 0.54762411, 0.44455962, 0.67525447,
       0.95685862, 0.83630232, 0.44309325, 0.58614074, 0.30871484])

In [ ]:
np.random.rand(4,2)

array([[0.79517587, 0.06235944],
       [0.92949557, 0.7708081 ],
       [0.90669676, 0.20346709],
       [0.7496967 , 0.28528155]])

?6) Create a 1X10 array of random nos between 0 and 1 using random function.

Create an array of order 4X2 with random nos between 0 and 1 using random function

In [ ]:
np.random.random(100)

array([0.64695655, 0.09904225, 0.25000029, 0.53880638, 0.3976413 ,
       0.87498756, 0.72886259, 0.98448689, 0.01066272, 0.47504674,
       0.14978336, 0.0609837 , 0.86178706, 0.21715843, 0.42850662,
       0.78626267, 0.06023808, 0.14959982, 0.94591504, 0.97415749,
       0.37960245, 0.74794811, 0.14170775, 0.1463379 , 0.7853052 ,
       0.66222488, 0.81226184, 0.01169265, 0.34723477, 0.56426809,
       0.67402109, 0.46099577, 0.74975015, 0.30139116, 0.33002322,
       0.76864965, 0.45075281, 0.70380588, 0.16001582, 0.91669076,
       0.22795866, 0.75035813, 0.17197939, 0.29379049, 0.49809026,
       0.85422687, 0.89047111, 0.51537149, 0.19692042, 0.98737628,
       0.47702069, 0.22777797, 0.06611987, 0.21681349, 0.33339366,
       0.23858789, 0.80896457, 0.81964531, 0.77819328, 0.25451846,
       0.05969633, 0.90217588, 0.18353834, 0.52943091, 0.89392964,
       0.2494386 , 0.28446597, 0.00967176, 0.07563368, 0.21974473,
       0.13576879, 0.4567044 , 0.94769334, 0.18893535, 0.27160

In [ ]:
np.random.random((4,2))

array([[0.49520839, 0.19241253],
       [0.39482062, 0.24783932],
       [0.34697899, 0.17354238],
       [0.56498323, 0.47775475]])

?7) Select a random integer between 20 and 300 using randint
1. Make a 2X3 matrix using randint with integer values between 0 and 5

In [ ]:
np.random.randint(20,300)

275

In [ ]:
np.random.randint(0,5,size=(2,3))

array([[1, 2, 2],
       [3, 3, 1]])

?8) Return a 1-D array of 10 nos from **standard normal distribution**

Create an 2X3 matrix with values of std normal distribution

In [ ]:
np.random.randn(10)

array([ 1.73823536, -0.08480494, -1.16224542, -0.16579156, -1.70492897,
        1.14410201, -0.44487936,  1.7430003 , -0.39453208, -1.02046717])

In [ ]:
np.random.randn(2,3)

array([[-0.99473976,  1.04460998, -1.92437524],
       [ 0.85134821,  0.84434782, -0.84691882]])

?9) Create a 2X3 matrix with zeros.

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

?10) Create a 2X3 matrix with ones.

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

?11) Return a 1-D array of 10 nos from continuous uniform distribution

1. Create a matrix in the shape of 'a' with values of **continuous uniform distribution**
2. Multiply the above created matrix by 10 and round up the elements

In [ ]:
np.random.random_sample(10)

array([0.39280105, 0.95976413, 0.35811505, 0.01821269, 0.79433869,
       0.82138866, 0.80785083, 0.10661656, 0.05998384, 0.47174649])

In [ ]:
p=np.random.random_sample(a.shape)

In [ ]:
np.round(10*p)

array([[9., 4., 4.],
       [2., 1., 6.]])

#**LINSPACE**
Gives evenly spaced values between two specified start and stop(both inclusive).

In [ ]:
np.linspace?

In [ ]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
len(np.linspace(1,10))

50

Without specifying the no of elements, linspace gives 50 elements

In [ ]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
np.linspace(1,10,num = 20, endpoint=False)

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

?12) Create a scalar matrix of order 3X3 with element 30

Multiply all the elements of this matrix with 10

In [ ]:
np.full((3,3),30)

array([[30, 30, 30],
       [30, 30, 30],
       [30, 30, 30]])

In [ ]:
np.full((3,3),30)*10

array([[300, 300, 300],
       [300, 300, 300],
       [300, 300, 300]])

?13) Create a 3X3 identity matrix

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#**SLICING**

##SLICING 1-D array

In [ ]:
import numpy as np

In [ ]:
dat = np.array([1,2,3,4])
dat[0:2]

array([1, 2])

##SLICING 2-D array

In [ ]:
dat = np.array([[1,2,3],[4,5,6]])

In [ ]:
dat[0]

array([1, 2, 3])

In [ ]:
dat[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
dat[0,0]

1

In [ ]:
dat[1,2]

6

In [ ]:
dat[:,1:]

array([[2, 3],
       [5, 6]])

##SLICING 3-D array

In [ ]:
dat = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])

In [ ]:
dat

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
dat[0:2]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
dat[0:2,1:]

array([[[ 3,  4],
        [ 5,  6]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
dat[0:2,1:,0:]

array([[[ 3,  4],
        [ 5,  6]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
dat[0:2,1:,1]

array([[ 4,  6],
       [10, 12]])

In [ ]:
a = np.random.rand(20)

In [ ]:
a

array([0.04927098, 0.5680424 , 0.28504621, 0.06340051, 0.44665239,
       0.59298719, 0.84593718, 0.75883699, 0.77085774, 0.76573266,
       0.15814268, 0.87229924, 0.11851249, 0.64301873, 0.91034994,
       0.87691425, 0.50112536, 0.57593374, 0.50307708, 0.2995352 ])

In [ ]:
a[::2]

array([0.04927098, 0.28504621, 0.44665239, 0.84593718, 0.77085774,
       0.15814268, 0.11851249, 0.91034994, 0.50112536, 0.50307708])

In [ ]:
a[::-2]

array([0.2995352 , 0.57593374, 0.87691425, 0.64301873, 0.87229924,
       0.76573266, 0.75883699, 0.59298719, 0.06340051, 0.5680424 ])

?14) Create a 2X3 matrix with first 6 natural nos.
   1. Find the index of element 4
   2. Substitute element 4 with 44


In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,7).reshape(2,3)

In [ ]:
idx = np.argwhere(a==4)

In [ ]:
idx[0]


array([1, 0])

In [ ]:
tuple(idx[0])


(1, 0)

##**NOTE THIS** 

In [ ]:
idx[0][0]

1

In [ ]:
idx[0,0]

1

?15) Create a 1-D array of first 7 natural nos.
1. Find the index of element 4
2. Substitute element 4 with 44

In [ ]:
a = np.arange(1,8)

In [ ]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
idx = np.argwhere(a==4)

In [ ]:
idx[0][0]

3

In [ ]:
a[idx] = 44

In [ ]:
a

array([ 1,  2,  3, 44,  5,  6,  7])

?16) Make a random 3X3 matrix and assign it to mat


    1. Find transpose of mat
    2. Find inverse of mat
    3. Sort each column of mat
    4. Sort each row of mat



In [ ]:
mat = np.random.randint(1,10,size=(3,3))

In [ ]:
mat

array([[7, 9, 4],
       [3, 8, 3],
       [3, 6, 7]])

In [ ]:
mat.T

array([[7, 3, 3],
       [9, 8, 6],
       [4, 3, 7]])

In [ ]:
np.transpose(mat)

array([[7, 3, 3],
       [9, 8, 6],
       [4, 3, 7]])

In [ ]:
import numpy.linalg as la
la.inv(mat)

array([[ 0.28358209, -0.29104478, -0.03731343],
       [-0.08955224,  0.2761194 , -0.06716418],
       [-0.04477612, -0.1119403 ,  0.21641791]])

In [ ]:
mat.sort(axis = 0)

In [ ]:
mat

array([[3, 6, 3],
       [3, 8, 4],
       [7, 9, 7]])

In [ ]:
mat.sort(axis = 1)

In [ ]:
mat

array([[3, 3, 6],
       [3, 4, 8],
       [7, 7, 9]])

?17) Make a 1-D integer array by flattening a 4X5 matrix and assign it to check

    1. Pick the elements at indices 1,4 and 6 and display them as a 1-D array by masking
    3. Display the element less than 8 in an array
    4. Display the element less than 8 and greater than 4 in an array
    5. Demonstrate boolean masking
    6. Reverse back check into a 4X5 matrix
    7. Display the corner elements of check in a 1-D array
    8. Display the corner elements of check in 2X2 matrix



#**NB:** You get a copy when you mask unlike in slicing. You get a view when you slice

In [ ]:
check = np.random.randint(1,21,size=(4,5)).flatten()

In [ ]:
check

array([ 1, 19, 19,  4,  7,  5, 11, 11, 10, 14,  9,  7,  7,  8,  7,  4, 10,
       13,  3, 19])

In [ ]:
check[[1,4,6]]

array([19,  7, 11])

In [ ]:
check[check<8]

array([1, 4, 7, 5, 7, 7, 7, 4, 3])

In [ ]:
check[(check<8) & (check>4)]

array([7, 5, 7, 7, 7])

In [ ]:
check[(check<8) and (check>4)]

ValueError: ignored

#**NB:** **'&'** is used when operands are arrays. **'and'** does not work for array.
Similar for some other operators as well
   

*   & - and
*   | - or



*   ~ - not


   
   

In [ ]:
demo = np.array([6,4,3.2,3])
demo[[True,False,True,True]]

array([6. , 3.2, 3. ])

In [ ]:
check = check.reshape(4,5)

In [ ]:
check

array([[ 1, 19, 19,  4,  7],
       [ 5, 11, 11, 10, 14],
       [ 9,  7,  7,  8,  7],
       [ 4, 10, 13,  3, 19]])

In [ ]:
check[[0,0,3,3],[0,4,0,4]]

array([ 1,  7,  4, 19])

In [ ]:
rows = [[0,0],[3,3]]
cols = [[0,4],[0,4]]
check[rows,cols]

array([[ 1,  7],
       [ 4, 19]])

#**BROADCASTING**

In [ ]:
A = np.array([1,2,3,4]).reshape(2,2)

In [ ]:
A += 5

In [ ]:
A

array([[6, 7],
       [8, 9]])

Python interprets '5' as a 2X2 scalar matrix of 5s

In [ ]:
B= np.array([2,3,5,9]).reshape(2,2)
C = np.array([1,3]).reshape(2,1)
B+C

array([[ 3,  4],
       [ 8, 12]])

Here C is interpreted as [[1,1],[3,3]]

In [ ]:
B= np.array([2,3,5,9]).reshape(2,2)
C = np.array([1,3,7])
B+C

ValueError: ignored

#**ValueError: operands could not be broadcast together with shapes (2,2) (3,) **


?18) Make a 2X3 matrix with first 6 natural nos. and assign it to A



    1.  Concatenate a 2X2 matrix to A 
    2.  Concatenate a 4X3 matrix to A




In [ ]:
A = np.arange(1,7).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
B = (np.round(10*np.random.rand(4))).reshape(2,2)
B

array([[7., 4.],
       [8., 6.]])

In [ ]:
np.hstack((A,B))

array([[1., 2., 3., 7., 4.],
       [4., 5., 6., 8., 6.]])

In [ ]:
B = (np.round(10*np.random.rand(12))).reshape(4,3)
B

array([[ 5.,  7.,  8.],
       [ 1.,  8.,  2.],
       [10.,  6.,  9.],
       [ 6.,  3.,  3.]])

In [ ]:
np.vstack((A,B))

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 5.,  7.,  8.],
       [ 1.,  8.,  2.],
       [10.,  6.,  9.],
       [ 6.,  3.,  3.]])

?19) Make a random 1-D array with random permutation function and assign it into p

   1. Sort p in ascending order
   2. Sort p in desceding order

**RESTORE A**
   3. Find the largest element in A w/o sorting
   4. Find the smallest element in A w/o sorting
   5. Find the index of largest element in A
   6. Find the index of smallest element in A
   7. Find the square of all elements of A and put it in a matrix
   8. Find the standard deviation of all elements in A


In [ ]:
import numpy as np

In [ ]:
A = np.round(10*np.random.rand(20))

In [ ]:
A

array([ 4.,  0.,  8.,  1.,  3.,  2.,  6.,  7.,  4.,  9.,  2.,  3.,  7.,
        4.,  7., 10.,  1.,  0.,  3.,  3.])

In [ ]:
np.sort(A)

array([ 0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,
        6.,  7.,  7.,  7.,  8.,  9., 10.])

In [ ]:
A # No permanent change to A

array([ 4.,  0.,  8.,  1.,  3.,  2.,  6.,  7.,  4.,  9.,  2.,  3.,  7.,
        4.,  7., 10.,  1.,  0.,  3.,  3.])

In [ ]:
A.sort()

In [ ]:
A # A got permanently altered

array([ 0.,  0.,  1.,  1.,  2.,  2.,  3.,  3.,  3.,  3.,  4.,  4.,  4.,
        6.,  7.,  7.,  7.,  8.,  9., 10.])

In [ ]:
A = A[::-1] #Sorted A got reversed

In [ ]:
A

array([10.,  9.,  9.,  9.,  8.,  7.,  6.,  6.,  6.,  5.,  5.,  5.,  4.,
        4.,  4.,  3.,  3.,  3.,  2.,  1.])

In [ ]:
A.max()

9.0

In [ ]:
A.min()

0.0

In [ ]:
A.argmax()

9

In [ ]:
A.argmin()

0

In [ ]:
A ** 2

array([ 49., 100.,   4.,  49.,  36.,   9.,  25.,   4.,  36.,  36.,   4.,
        64.,   9.,   9.,  16.,   0.,  16.,  25.,   1.,  49.])

In [ ]:
np.std(A)

2.5194245374688244

?20) Demonstrate string array sorting.

In [ ]:
stri = np.array(['kuku','dragon','a','hi','kid'])


In [ ]:
stri

array(['kuku', 'dragon', 'a', 'hi', 'kid'], dtype='<U6')

In [ ]:
stri.sort()

In [ ]:
stri

array(['a', 'dragon', 'hi', 'kid', 'kuku'], dtype='<U6')

In [ ]:
np.random.random((2,3)).seed(101)

AttributeError: ignored

In [ ]:
np.random.random((23,4)).seed(191)
                              

AttributeError: ignored

**To find the coefficient of correlation use the function, np.corrcoef()**